### ISSUE TITLE
i cannot find the result picture

### ISSUE THREAD

**Issue by Lvhhhh** [LinHungShi/GCNetwork#8]
thanks for your work! i download it and want to test it performance. but after the command. i found no picture on my result folder.
this is my command,
"python test.py -data ./pic"
(the 'pic ' is the folder where i put my test pictures in 'left' and 'right',such as"./pic/left/0l.png"and "./pic/right/0r.png")

the content on the 'test_params.json' are:
"{
	"pspath": "./res",
	"batch_size": 1,
	"w_path": "./model/pretrained_model_weight.hdf5",
	"max_q_size": 3,
	"verbose": 1
}
"
the content on the 'util_param.json' are:
"{
	"crop_width": 128, 
        "crop_height": 96,
        "new_max": 1,
        "new_min": -1,
        "old_max": 256,
        "old_min": 0,
        "val_ratio": 0.1,
	"file_extension": "png",
	"seed": 1234,
	"fraction": 1
}
"
thank you for your help!

**Comment by LinHungShi** [comment]
Hi, could you please post parts of the message?  
Btw,  I am still training the model with the SceneFlow dataset, so the result might not be good.

**Comment by Lvhhhh** [comment]
okay.here is the message~

8] Chunk at 0x102080a6100 of size 256
2017-09-16 09:41:52.684973: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x102080a6200 of size 256
2017-09-16 09:41:52.684979: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x102080a6300 of size 256
2017-09-16 09:41:52.684986: I tensorflow/core/common_runtime/bfc_allocator.cc:678] Chunk at 0x102080a6400 of size 695296
2017-09-16 09:41:52.684994: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x10208001200 of size 9728
2017-09-16 09:41:52.685000: I tensorflow/core/common_runtime/bfc_allocator.cc:687] Free at 0x10208097900 of size 36864
2017-09-16 09:41:52.685006: I tensorflow/core/common_runtime/bfc_allocator.cc:693]      Summary of in-use Chunks by size: 
2017-09-16 09:41:52.685024: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 169 Chunks of size 256 totalling 42.2KiB
2017-09-16 09:41:52.685032: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 1280 totalling 1.2KiB
2017-09-16 09:41:52.685041: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 16 Chunks of size 36864 totalling 576.0KiB
2017-09-16 09:41:52.685049: I tensorflow/core/common_runtime/bfc_allocator.cc:696] 1 Chunks of size 695296 totalling 679.0KiB
2017-09-16 09:41:52.685056: I tensorflow/core/common_runtime/bfc_allocator.cc:700] Sum Total of in-use chunks: 1.27MiB
2017-09-16 09:41:52.685102: I tensorflow/core/common_runtime/bfc_allocator.cc:702] Stats: 
Limit:                     1376256
InUse:                     1329664
MaxInUse:                  1376256
NumAllocs:                     205
MaxAllocSize:               695296

2017-09-16 09:41:52.685126: W tensorflow/core/common_runtime/bfc_allocator.cc:277] **********************************************_***********************************xxxxxxxxxxxxxxxxxx
2017-09-16 09:41:52.685154: W tensorflow/core/framework/op_kernel.cc:1158] Resource exhausted: OOM when allocating tensor with shape[3,3,3,64,64]
Traceback (most recent call last):
  File "test.py", line 31, in <module>
    model.load_weights(weight_path)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 2619, in load_weights
    load_weights_from_hdf5_group(f, self.layers)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 3095, in load_weights_from_hdf5_group
    K.batch_set_value(weight_value_tuples)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 2193, in batch_set_value
    get_session().run(assign_ops, feed_dict=feed_dict)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 167, in get_session
    _initialize_variables()
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 341, in _initialize_variables
    sess.run(tf.variables_initializer(uninitialized_variables))
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 789, in run
    run_metadata_ptr)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 997, in _run
    feed_dict_string, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1132, in _do_run
    target_list, options, run_metadata)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/client/session.py", line 1152, in _do_call
    raise type(e)(node_def, op, message)
tensorflow.python.framework.errors_impl.ResourceExhaustedError: OOM when allocating tensor with shape[3,3,3,64,64]
	 [[Node: conv3d_transpose_2/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=5427957, _device="/job:localhost/replica:0/task:0/gpu:0"](conv3d_transpose_2/random_uniform/shape)]]

Caused by op u'conv3d_transpose_2/random_uniform/RandomUniform', defined at:
  File "test.py", line 30, in <module>
    model = createGCNetwork(hp)
  File "src/gcnetwork.py", line 151, in createGCNetwork
    disp_map = _LearnReg_(cv, num_filters, ksize, ds_stride, resnet, padding, highway_func, num_down_conv)
  File "src/gcnetwork.py", line 123, in _LearnReg_
    deconv = _createDeconv3D_(up_convs, 2 * base_num_filters, ksize, ds_stride, padding)
  File "src/gcnetwork.py", line 44, in _createDeconv3D_
    deconv = Conv3DTranspose(filters, ksize, stride, padding) (input)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 575, in __call__
    self.build(input_shapes[0])
  File "src/conv3dTranspose.py", line 209, in build
    constraint=self.kernel_constraint)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/topology.py", line 396, in add_weight
    weight = K.variable(initializer(shape),
  File "/usr/local/lib/python2.7/dist-packages/keras/initializers.py", line 212, in __call__
    dtype=dtype, seed=self.seed)
  File "/usr/local/lib/python2.7/dist-packages/keras/backend/tensorflow_backend.py", line 3544, in random_uniform
    dtype=dtype, seed=seed)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/random_ops.py", line 236, in random_uniform
    shape, dtype, seed=seed1, seed2=seed2)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/ops/gen_random_ops.py", line 249, in _random_uniform
    seed=seed, seed2=seed2, name=name)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/op_def_library.py", line 767, in apply_op
    op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 2506, in create_op
    original_op=self._default_original_op, op_def=op_def)
  File "/usr/local/lib/python2.7/dist-packages/tensorflow/python/framework/ops.py", line 1269, in __init__
    self._traceback = _extract_stack()

ResourceExhaustedError (see above for traceback): OOM when allocating tensor with shape[3,3,3,64,64]
	 [[Node: conv3d_transpose_2/random_uniform/RandomUniform = RandomUniform[T=DT_INT32, dtype=DT_FLOAT, seed=87654321, seed2=5427957, _device="/job:localhost/replica:0/task:0/gpu:0"](conv3d_transpose_2/random_uniform/shape)]]

my nvidia is 1060 . maybe  the memory is not enough?

**Comment by Lvhhhh** [comment]
the size of my test picutre is 128 96....and i dont know how to make it works

**Comment by Lvhhhh** [comment]
now. it have these problem
sing TensorFlow backend.
2017-09-16 10:22:56.473879: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-16 10:22:56.473910: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-16 10:22:56.473918: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-16 10:22:56.601133: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-16 10:22:56.601492: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1060 6GB
major: 6 minor: 1 memoryClockRate (GHz) 1.7845
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.58GiB
2017-09-16 10:22:56.601512: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-09-16 10:22:56.601521: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-09-16 10:22:56.601532: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0)
Predict data using generator...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
StopIteration

Traceback (most recent call last):
  File "test.py", line 49, in <module>
    pred = model.predict_generator(generator, max_queue_size = max_q_size, steps = bs, verbose = verbose)
  File "/usr/local/lib/python2.7/dist-packages/keras/legacy/interfaces.py", line 87, in wrapper
    return func(*args, **kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/engine/training.py", line 2272, in predict_generator
    generator_output = next(output_generator)
StopIteration

**Comment by LinHungShi** [comment]
Hi, please set max_q_size to 1, then test your model again. Show me the error message if it still occurs.

**Comment by Lvhhhh** [comment]
the  test_params.json
{
	"data":"./pic",
	"pspath": "./prediction",
	"batch_size": 1,
	"w_path": "model_weight.hdf5",
	"max_q_size": 1,
	"verbose": 1
}



the error message:

Using TensorFlow backend.
Loading pretrained cost weight...
2017-09-18 13:54:29.217078: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.1 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-18 13:54:29.217100: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use SSE4.2 instructions, but these are available on your machine and could speed up CPU computations.
2017-09-18 13:54:29.217107: W tensorflow/core/platform/cpu_feature_guard.cc:45] The TensorFlow library wasn't compiled to use AVX instructions, but these are available on your machine and could speed up CPU computations.
2017-09-18 13:54:29.342172: I tensorflow/stream_executor/cuda/cuda_gpu_executor.cc:893] successful NUMA node read from SysFS had negative value (-1), but there must be at least one NUMA node, so returning NUMA node zero
2017-09-18 13:54:29.342498: I tensorflow/core/common_runtime/gpu/gpu_device.cc:940] Found device 0 with properties: 
name: GeForce GTX 1060 6GB
major: 6 minor: 1 memoryClockRate (GHz) 1.7845
pciBusID 0000:01:00.0
Total memory: 5.93GiB
Free memory: 5.59GiB
2017-09-18 13:54:29.342513: I tensorflow/core/common_runtime/gpu/gpu_device.cc:961] DMA: 0 
2017-09-18 13:54:29.342519: I tensorflow/core/common_runtime/gpu/gpu_device.cc:971] 0:   Y 
2017-09-18 13:54:29.342528: I tensorflow/core/common_runtime/gpu/gpu_device.cc:1030] Creating TensorFlow device (/gpu:0) -> (device: 0, name: GeForce GTX 1060 6GB, pci bus id: 0000:01:00.0)
Predict data using generator...
Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python2.7/threading.py", line 801, in __bootstrap_inner
    self.run()
  File "/usr/lib/python2.7/threading.py", line 754, in run
    self.__target(*self.__args, **self.__kwargs)
  File "/usr/local/lib/python2.7/dist-packages/keras/utils/data_utils.py", line 568, in data_generator_task
    generator_output = next(self._generator)
StopIteration

1/1 [==============================] - 1s

Process finished with exit code 0

**Comment by Lvhhhh** [comment]
1.i use the newest version of your code.
when i python train.py i found the loss is bigger and bigger. 
train_params.json are followed:
{
	"weight_save_path": "model/model_weight.hdf5",
        "period": 1,
        "verbose": 1, 
        "log_save_path": "log",
	"max_q_size": 1,
        "save_best_only": 1,
	"weight_path": "model/pretrained_model_weight.hdf5",
	"learning_rate": 0.001,
        "batch_size": 1,
        "epochs": 1,
	"epsilon": 0.00000001,
	"rho": 0.9,
	"decay": 0.0,
	"loss_function": "mean_absolute_error",
	"cost_volume_weight_save_path": "model/cost_weight.hdf5",
	"cost_volume_weight_path": "model/cost_weight.hdf5",
	"linear_output_weight_save_path": "model/linear_output_weight.hdf5",
	"linear_output_weight_path": "model/linear_output_weight.hdf5",  
	"pspath": "./prediction",
	"psdata":"./pic"
}

here are the environment.json
{
	"sceneflow_root": "/home/lvhao/data/",
	"driving_root": "driving",
	"driving_train": "frames_cleanpass",
	"driving_label": "disparity",
	"monkaa_root": "monkaa",
	"monkaa_train": "frames_cleanpass",
	"monkaa_label": "disparity",
	"train_all": 0,
	"train_driving": 1,
	"train_monkaa": 0
}
(i just use the driving sample)
2.in test.py i make some changes:
add a line"psdata = tp['psdata']" behind the line23"pspath = tp['pspath']"
and change the line  27 to
"parser.add_argument('-data', help = 'data used for prediction',  default = psdata)"
and i set the left and right test pictures such as "./pic/left/0_left.png"and "./pic/right/0_right.png". 
(because i want to just input the  'python test.py')
here are all changes i make .
i dont know why it does not work!
thank you for your time!

**Comment by Lvhhhh** [comment]
the message of util_params.json are here:
{
	"crop_width": 128,
        "crop_height": 128,
        "val_ratio": 0.1,
	"file_extension": "png",
	"seed": 1234,
	"fraction": 1 
}

**Comment by LinHungShi** [comment]
1. Hi, the error occurs because you feed only one data sample. However, you should see the prediction result in the directory.
2. What value do you set for pspath?
3. Since the model is trained with patches randomly cropped from images, it requires lots of epochs before the convergence. I am still training the model with the Driving and Monkaa dataset, and will upload the result to Github as soon as possible.

**Comment by Lvhhhh** [comment]
hi. after i copy the '0l.png' to '0l.png' and '1l.png'(the same as the right images) .the error message disappered . i can use PIL to show the result image~
now i want to know:why only one data sample make error message?
thanks! and i am looking forward to your training result!!

**Comment by guandog** [comment]
six six six
